
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  h2.console.enable: true
cds:
  datasource.auto-config.enabled: false

logging:
  level.com.zaxxer.hikari.HikariConfig: DEBUG

server.port: 8081
